<a href="https://colab.research.google.com/github/Poojav21/ML-Projects/blob/main/Loan_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("/content/train_loan.csv")

In [3]:
data.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [4]:
data.tail()

Loan_ID  Gender Married Dependents Education Self_Employed  \
609  LP002978  Female      No          0  Graduate            No   
610  LP002979    Male     Yes         3+  Graduate            No   
611  LP002983    Male     Yes          1  Graduate            No   
612  LP002984    Male     Yes          2  Graduate            No   
613  LP002990  Female      No          0  Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N

In [5]:
data.shape

(614, 13)

In [6]:
print("Number of rows", data.shape[0])
print("Number of rows", data.shape[1])

Number of rows 614
Number of rows 13


In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [8]:
data.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [9]:
data.isnull().sum()*100/len(data)

Loan_ID              0.000000
Gender               2.117264
Married              0.488599
Dependents           2.442997
Education            0.000000
Self_Employed        5.211726
ApplicantIncome      0.000000
CoapplicantIncome    0.000000
LoanAmount           3.583062
Loan_Amount_Term     2.280130
Credit_History       8.143322
Property_Area        0.000000
Loan_Status          0.000000
dtype: float64

In [10]:
# handling the missing values
data = data.drop("Loan_ID", axis = 1)

In [11]:
data.head(1)

Gender Married Dependents Education Self_Employed  ApplicantIncome  \
0   Male      No          0  Graduate            No             5849   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0         NaN             360.0             1.0   

  Property_Area Loan_Status  
0         Urban           Y

In [12]:
columns = ["Gender",'Dependents','LoanAmount','Loan_Amount_Term']


In [13]:
data = data.dropna(subset = columns)

In [14]:
data.isnull().sum()*100/len(data)

Gender               0.000000
Married              0.000000
Dependents           0.000000
Education            0.000000
Self_Employed        5.424955
ApplicantIncome      0.000000
CoapplicantIncome    0.000000
LoanAmount           0.000000
Loan_Amount_Term     0.000000
Credit_History       8.679928
Property_Area        0.000000
Loan_Status          0.000000
dtype: float64

In [15]:
data['Self_Employed'].mode()[0]

'No'

In [16]:
data['Self_Employed'] = data['Self_Employed'].fillna(data['Self_Employed'].mode()[0])

In [17]:
data.isnull().sum()*100/len(data)

Gender               0.000000
Married              0.000000
Dependents           0.000000
Education            0.000000
Self_Employed        0.000000
ApplicantIncome      0.000000
CoapplicantIncome    0.000000
LoanAmount           0.000000
Loan_Amount_Term     0.000000
Credit_History       8.679928
Property_Area        0.000000
Loan_Status          0.000000
dtype: float64

In [18]:
data['Credit_History'].unique()

array([ 1.,  0., nan])

In [19]:
data['Credit_History'] = data['Credit_History'].fillna(data['Credit_History'].mode()[0])

In [20]:
data.isnull().sum()*100/len(data)

Gender               0.0
Married              0.0
Dependents           0.0
Education            0.0
Self_Employed        0.0
ApplicantIncome      0.0
CoapplicantIncome    0.0
LoanAmount           0.0
Loan_Amount_Term     0.0
Credit_History       0.0
Property_Area        0.0
Loan_Status          0.0
dtype: float64

In [21]:
data.sample(5)

Gender Married Dependents Education Self_Employed  ApplicantIncome  \
370  Female      No          0  Graduate           Yes            15759   
488    Male     Yes          2  Graduate           Yes             4583   
265    Male      No          0  Graduate            No             4095   
182    Male     Yes          0  Graduate            No             4600   
572    Male     Yes          2  Graduate            No            16666   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
370                0.0        55.0             360.0             1.0   
488             2083.0       160.0             360.0             1.0   
265             3447.0       151.0             360.0             1.0   
182                0.0        73.0             180.0             1.0   
572                0.0       275.0             360.0             1.0   

    Property_Area Loan_Status  
370     Semiurban           Y  
488     Semiurban           Y  
265         Rural           Y  
182     Semiurban           Y  
572         Urban           Y

In [22]:
data['Dependents'] = data['Dependents'].replace(to_replace = '3+', value = '4')

In [23]:
data.sample(5)

Gender Married Dependents Education Self_Employed  ApplicantIncome  \
82   Female     Yes          2  Graduate            No             1378   
476    Male     Yes          2  Graduate            No             6700   
302  Female      No          0  Graduate            No             5000   
433    Male     Yes          0  Graduate            No             2425   
286  Female      No          0  Graduate           Yes             2600   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
82              1881.0       167.0             360.0             1.0   
476             1750.0       230.0             300.0             1.0   
302                0.0       132.0             360.0             1.0   
433             2340.0       143.0             360.0             1.0   
286             1717.0        99.0             300.0             1.0   

    Property_Area Loan_Status  
82          Urban           N  
476     Semiurban           Y  
302         Rural           Y  
433     Semiurban           Y  
286     Semiurban           N

In [24]:
data['Dependents'].unique()

array(['1', '0', '2', '4'], dtype=object)

In [25]:
data['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [26]:
data.isnull().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [27]:
data['Gender'] = data['Gender'].map({'Male':1, 'Female':0}).astype('int')

In [28]:
data['Gender'].unique()

array([1, 0])

In [29]:
data['Married'] = data['Married'].map({'Yes':1, 'No':0}).astype('int')

In [30]:
data['Married'].unique()

array([1, 0])

In [31]:
data['Education'].unique() 

array(['Graduate', 'Not Graduate'], dtype=object)

In [32]:
data['Education'] = data['Education'].map({'Graduate':1, 'Not Graduate':0}).astype('int')

In [33]:
data['Education'].unique()

array([1, 0])

In [34]:
data['Self_Employed'] = data['Self_Employed'].map({'Yes':1, 'No':0}).astype('int')

In [35]:
data['Self_Employed'].unique()

array([0, 1])

In [36]:
data['Property_Area'] = data['Property_Area'].map({'Urban':1, 'Rural':0, 'Semiurban':2}).astype('int')

In [37]:
data['Property_Area'].unique()

array([0, 1, 2])

In [38]:
data['Loan_Status'] = data['Loan_Status'].map({'Y':1, 'N':0}).astype('int')

In [39]:
data['Loan_Status'].unique()

array([0, 1])

In [40]:
data.head()

Gender  Married Dependents  Education  Self_Employed  ApplicantIncome  \
1       1        1          1          1              0             4583   
2       1        1          0          1              1             3000   
3       1        1          0          0              0             2583   
4       1        0          0          1              0             6000   
5       1        1          2          1              1             5417   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   
5             4196.0       267.0             360.0             1.0   

   Property_Area  Loan_Status  
1              0            0  
2              1            1  
3              1            1  
4              1            1  
5              1            1

In [41]:
X = data.drop('Loan_Status', axis = 1)
X

Gender  Married Dependents  Education  Self_Employed  ApplicantIncome  \
1         1        1          1          1              0             4583   
2         1        1          0          1              1             3000   
3         1        1          0          0              0             2583   
4         1        0          0          1              0             6000   
5         1        1          2          1              1             5417   
..      ...      ...        ...        ...            ...              ...   
609       0        0          0          1              0             2900   
610       1        1          4          1              0             4106   
611       1        1          1          1              0             8072   
612       1        1          2          1              0             7583   
613       0        0          0          1              1             4583   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
1               1508.0       128.0             360.0             1.0   
2                  0.0        66.0             360.0             1.0   
3               2358.0       120.0             360.0             1.0   
4                  0.0       141.0             360.0             1.0   
5               4196.0       267.0             360.0             1.0   
..                 ...         ...               ...             ...   
609                0.0        71.0             360.0             1.0   
610                0.0        40.0             180.0             1.0   
611              240.0       253.0             360.0             1.0   
612                0.0       187.0             360.0             1.0   
613                0.0       133.0             360.0             0.0   

     Property_Area  
1                0  
2                1  
3                1  
4                1  
5                1  
..             ...  
609              0  
610              0  
611              1  
612              1  
613              2  

[553 rows x 11 columns]

In [42]:
y = data['Loan_Status']
y

1      0
2      1
3      1
4      1
5      1
      ..
609    1
610    1
611    1
612    1
613    0
Name: Loan_Status, Length: 553, dtype: int64

In [43]:
data.head()

Gender  Married Dependents  Education  Self_Employed  ApplicantIncome  \
1       1        1          1          1              0             4583   
2       1        1          0          1              1             3000   
3       1        1          0          0              0             2583   
4       1        0          0          1              0             6000   
5       1        1          2          1              1             5417   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   
5             4196.0       267.0             360.0             1.0   

   Property_Area  Loan_Status  
1              0            0  
2              1            1  
3              1            1  
4              1            1  
5              1            1

In [44]:
cols = ['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term' ]

In [45]:
from sklearn.preprocessing import StandardScaler
st = StandardScaler()
X[cols] = st.fit_transform(X[cols])

In [46]:
X

Gender  Married Dependents  Education  Self_Employed  ApplicantIncome  \
1         1        1          1          1              0        -0.128694   
2         1        1          0          1              1        -0.394296   
3         1        1          0          0              0        -0.464262   
4         1        0          0          1              0         0.109057   
5         1        1          2          1              1         0.011239   
..      ...      ...        ...        ...            ...              ...   
609       0        0          0          1              0        -0.411075   
610       1        1          4          1              0        -0.208727   
611       1        1          1          1              0         0.456706   
612       1        1          2          1              0         0.374659   
613       0        0          0          1              1        -0.128694   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
1            -0.049699   -0.214368          0.279961             1.0   
2            -0.545638   -0.952675          0.279961             1.0   
3             0.229842   -0.309634          0.279961             1.0   
4            -0.545638   -0.059562          0.279961             1.0   
5             0.834309    1.440866          0.279961             1.0   
..                 ...         ...               ...             ...   
609          -0.545638   -0.893134          0.279961             1.0   
610          -0.545638   -1.262287         -2.468292             1.0   
611          -0.466709    1.274152          0.279961             1.0   
612          -0.545638    0.488213          0.279961             1.0   
613          -0.545638   -0.154828          0.279961             0.0   

     Property_Area  
1                0  
2                1  
3                1  
4                1  
5                1  
..             ...  
609              0  
610              0  
611              1  
612              1  
613              2  

[553 rows x 11 columns]

In [47]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
import numpy as np

In [48]:
model_df = {}
def model_val(model, X, y):
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 42)
  
  model.fit(X_train, y_train)
  y_pred = model.predict(X_test)
  print(f"{model} accuracy is {accuracy_score(y_test, y_pred)}")

  score = cross_val_score(model, X, y , cv = 5)
  print(f"{model} average cross val score is {np.mean(score)}")
  model_df[model] = round(np.mean(score)*100, 2)

In [56]:
model_df

{LogisticRegression(): 80.48,
 SVC(): 79.39,
 DecisionTreeClassifier(): 71.25,
 RandomForestClassifier(): 78.67,
 GradientBoostingClassifier(): 77.4}

Logistic regression

In [50]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model_val(model, X, y)

LogisticRegression() accuracy is 0.8018018018018018
LogisticRegression() average cross val score is 0.8047829647829647


SVC

In [51]:
from sklearn import svm
model = svm.SVC()
model_val(model, X, y)

SVC() accuracy is 0.7927927927927928
SVC() average cross val score is 0.7938902538902539


Decision Tree Classifier

In [52]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model_val(model, X, y)

DecisionTreeClassifier() accuracy is 0.7297297297297297
DecisionTreeClassifier() average cross val score is 0.7124979524979524


Random Forest Classifier

In [53]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model_val(model, X, y)

RandomForestClassifier() accuracy is 0.7567567567567568
RandomForestClassifier() average cross val score is 0.7866830466830468


Gradient boosting Classifier

In [55]:
from sklearn.ensemble import GradientBoostingClassifier
model = GradientBoostingClassifier()
model_val(model, X, y)

GradientBoostingClassifier() accuracy is 0.7927927927927928
GradientBoostingClassifier() average cross val score is 0.774004914004914


Hyperparameter Tuning

In [60]:
from sklearn.model_selection import RandomizedSearchCV

Logistic Regression

In [59]:
log_reg_grid = {"C":np.logspace(-4,4,20), "solver": ['liblinear']}

In [61]:
rs_log_reg = RandomizedSearchCV(LogisticRegression(), param_distributions = log_reg_grid, n_iter=20, cv=5, verbose=True )

In [62]:
rs_log_reg.fit(X,y)

Fitting 5 folds for each of 20 candidates, totalling 100 fits


RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_iter=20,
                   param_distributions={'C': array([1.00000000e-04, 2.63665090e-04, 6.95192796e-04, 1.83298071e-03,
       4.83293024e-03, 1.27427499e-02, 3.35981829e-02, 8.85866790e-02,
       2.33572147e-01, 6.15848211e-01, 1.62377674e+00, 4.28133240e+00,
       1.12883789e+01, 2.97635144e+01, 7.84759970e+01, 2.06913808e+02,
       5.45559478e+02, 1.43844989e+03, 3.79269019e+03, 1.00000000e+04]),
                                        'solver': ['liblinear']},
                   verbose=True)

In [63]:
rs_log_reg.best_score_

0.8047829647829647

In [64]:
rs_log_reg.best_params_

{'solver': 'liblinear', 'C': 0.23357214690901212}

SVC

In [65]:
svc_grid = {'C':[0.25,0.50,0.75,1], 'kernel':['linear']}

In [66]:
rs_svc=RandomizedSearchCV(svm.SVC(), param_distributions=svc_grid,cv=5, n_iter=20, verbose=True)

In [68]:
rs_svc.fit(X,y)

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py:305: UserWarning: The total space of parameters 4 is smaller than n_iter=20. Running 4 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(


Fitting 5 folds for each of 4 candidates, totalling 20 fits


RandomizedSearchCV(cv=5, estimator=SVC(), n_iter=20,
                   param_distributions={'C': [0.25, 0.5, 0.75, 1],
                                        'kernel': ['linear']},
                   verbose=True)

In [69]:
rs_svc.best_score_

0.8066011466011467

In [70]:
rs_svc.best_params_

{'kernel': 'linear', 'C': 0.25}

Random Forest **Classifier**

In [71]:
RandomForestClassifier()

RandomForestClassifier()

In [85]:
rs_grid = {'n_estimators':np.arange(10,1000,10),
 'max_features':['sqrt'], 
 'max_depth':[None, 3,5,10,20,30],
 'min_samples_split':[2,5,20,50,100],
 'min_samples_leaf':[1,2,5,10]
 }

In [86]:
rs_rf = RandomizedSearchCV(RandomForestClassifier(),param_distributions=rs_grid, n_iter=20, cv=5,verbose=True)

In [87]:
rs_rf.fit(X,y)

Fitting 5 folds for each of 20 candidates, totalling 100 fits


RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(), n_iter=20,
                   param_distributions={'max_depth': [None, 3, 5, 10, 20, 30],
                                        'max_features': ['sqrt'],
                                        'min_samples_leaf': [1, 2, 5, 10],
                                        'min_samples_split': [2, 5, 20, 50,
                                                              100],
                                        'n_estimators': array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260,
       270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390,
       400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520,
       530, 540, 550, 560, 570, 580, 590, 600, 610, 620, 630, 640, 650,
       660, 670, 680, 690, 700, 710, 720, 730, 740, 750, 760, 770, 780,
       790, 800, 810, 820, 830, 840, 850, 860, 870, 880, 890, 900, 910,
       920, 930, 940, 950, 960, 970, 980, 990])},
                   verbose=True)

In [83]:
rs_rf.best_score_

0.8084193284193285

In [84]:
rs_rf.best_params_

{'n_estimators': 290,
 'min_samples_split': 50,
 'min_samples_leaf': 1,
 'max_features': 'sqrt',
 'max_depth': 3}

In [ ]:
# LogisticRegression score before hyperparameter tuning:80.47
# LogisticRegression score after hyperparameter tuning:80.47

# SVC score before hyperparameter tuning: 79.38
# SVC score after hyperparameter tuning:80.66


# RandomForestClassifier score before hyperparameter tuning:77.40
# RandomForestClassifier score after hyperparameter tuning:80.84

Save The Model

In [88]:
X = data.drop('Loan_Status', axis=1)
y = data['Loan_Status']

In [89]:
rf = RandomForestClassifier(n_estimators=290,
  min_samples_split=50,
  min_samples_leaf=1,
  max_features='sqrt',
  max_depth=3)

In [90]:
rf.fit(X,y)

RandomForestClassifier(max_depth=3, min_samples_split=50, n_estimators=290)

In [91]:
import joblib

In [92]:
joblib.dump(rf,'loan_status_predict')

['loan_status_predict']

In [94]:
model = joblib.load('loan_status_predict')

In [95]:
import pandas as pd

In [101]:
df = pd.DataFrame({
    'Gender':1,
    'Married':1,
    'Dependents':2,
    'Education':0,
    'Self_Employed':0,
    'ApplicantIncome':0,
    'CoapplicantIncome':0.0,
    'LoanAmount':45,
    'Loan_Amount_Term':180,
    'Credit_History':0,
    'Property_Area':1

}, index=[0])

In [102]:
df

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        1           2          0              0                0   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0          45               180               0   

   Property_Area  
0              1

In [104]:
result = model.predict(df)

In [105]:
if result ==1:
  print("Loan Approved")
else:
  print("Loan Not Approved") 

Loan Not Approved
